name: Inspire
favicon: null
layout_spectrum: 1
typography_spectrum: 0.02987055736593902
title: Everything that will inspire you
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1f1e1d'
    - '#ffffff'
    - '#c6c6c6'
    - '#64635f'
    - '#92918a'
  brandStrength: 0.5
  lightness: 0
  saturation: 1
  rhythmicContrast: 1
purpose: []
